# contents of a minimal pyproject.toml 

[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build" 

[project] 
dynamic = ["version"] 
name = "example_package_walterfilho" 
dependencies = ["numpy"]
readme="README.md"

[tool.hatch]
version.path = "src/example_package_walterfilho/__init__.py"

[project.optional-dependencies]
test = ["pytest"]
